@baseUrl = http://localhost:3001/api

### Insert new match
# @name insertNewMatch
POST {{baseUrl}}/matches HTTP/1.1
Content-Type: application/json

{
    "gameId": 59156,
    "username": "alexisOver9000"
}

### Insert new match which should fail due to missing username
POST {{baseUrl}}/matches HTTP/1.1
Content-Type: application/json

{
    "gameId": 59156
}

### Insert new match which should fail due to invalid gameId
POST {{baseUrl}}/matches HTTP/1.1
Content-Type: application/json

{
    "gameId": "59156",
    "username": "alexisOver9000"
}

@matchId = {{insertNewMatch.response.body.$._id}}

### Add highlight to existing match
POST {{baseUrl}}/matches/{{matchId}}/highlights HTTP/1.1
Content-Type: application/json

{
    "timestamp": 360,
    "type": "kill",
    "videoSrc": "https://cloudinary.com/video/1"
}

### Add highlight to existing match should fail due to invalid matchId
POST {{baseUrl}}/matches/12j312ja25/highlights HTTP/1.1
Content-Type: application/json

{
    "timestamp": 450,
    "type": "kill",
    "videoSrc": "https://cloudinary.com/video/1"
}

### Add highlight to existing match should fail due to match(id) not found
POST {{baseUrl}}/matches/60f83c6f4fef2f3442a920a5/highlights HTTP/1.1
Content-Type: application/json

{
    "timestamp": 450,
    "type": "kill",
    "videoSrc": "https://cloudinary.com/video/1"
}

### Return all matches
GET {{baseUrl}}/matches HTTP/1.1