export type Example = () => JSX.Element;
export * from './Ads/Ads.examples';
export * from './AppHeader/AppHeader.examples';
export * from './Feed/Feed.examples';
export * from './MatchDetails/MatchDetails.examples';
export * from './MatchItem/MatchItem.examples';
export * from './Upload/Upload.examples';
export * from './User/User.example';
export * from './VideoHighlight/VideoHighlight.examples';
export * from './Highlight/Highlight.examples';
export * from './HighlightFeed/HighlightFeed.examples';
